### ISSUE TITLE
Model download unavailable

### ISSUE THREAD

**Issue by mathcass** [zijwang/talkdown#2]
Hi! 

I was looking to see how this model would work on alternate corpora but it looks like the model file doesn't exist at the [specified URL](https://github.com/zijwang/talkdown/blob/master/download_model.bash#L1).

Is there an alternate download location?

Thank you!

**Comment by zijwang** [comment]
Thanks for pointing it out. It should work now.

**Comment by mathcass** [comment]
Thank you! I don't know if this was unintended, but it seems like the training data (this [URL](https://nlp.stanford.edu/~zijwang/talkdown/talkdown.tar.gz)) is now unavailable.

**Comment by mathcass** [comment]
Actually, I think there's another issue going on. The asset at `https://nlp.stanford.edu/~zijwang/talkdown/pretrained_full.tar.gz` doesn't seem to be the pretrained model. It seems like it's the training data now. 🤔 When I download it, then unzip it, it has your train, test, dev JSONL files in it.

**Comment by mathcass** [comment]
As a follow-up, all looks good. Thank you again.

**Comment by zijwang** [comment]
It (really) should work now! Apologize for the delay – it took a while to get the correct files online.

**Comment by mathcass** [comment]
No problem at all, and thank you!
